// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Hl18RLEsYGtuUsnl3lZKgDioSsNgwqk',
    appId: '1:686444373137:web:514a1a778c825db4390b30',
    messagingSenderId: '686444373137',
    projectId: 'fete-de-la-sience',
    authDomain: 'fete-de-la-sience.firebaseapp.com',
    databaseURL: 'https://fete-de-la-sience-default-rtdb.firebaseio.com',
    storageBucket: 'fete-de-la-sience.appspot.com',
    measurementId: 'G-Y19G6JSDKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdHfu0gHVlFh4fi8S17eO5k_ZVJZ64q4g',
    appId: '1:686444373137:android:565e49342170bbbd390b30',
    messagingSenderId: '686444373137',
    projectId: 'fete-de-la-sience',
    databaseURL: 'https://fete-de-la-sience-default-rtdb.firebaseio.com',
    storageBucket: 'fete-de-la-sience.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtkJLDL-1X5DR7msFIcibB3xLQ0hHvW8Q',
    appId: '1:686444373137:ios:246b0c73c3d73800390b30',
    messagingSenderId: '686444373137',
    projectId: 'fete-de-la-sience',
    databaseURL: 'https://fete-de-la-sience-default-rtdb.firebaseio.com',
    storageBucket: 'fete-de-la-sience.appspot.com',
    iosClientId: '686444373137-tm81b98sejmohkbkrlah9o7q09odc562.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtkJLDL-1X5DR7msFIcibB3xLQ0hHvW8Q',
    appId: '1:686444373137:ios:acd7bb89fe91d481390b30',
    messagingSenderId: '686444373137',
    projectId: 'fete-de-la-sience',
    databaseURL: 'https://fete-de-la-sience-default-rtdb.firebaseio.com',
    storageBucket: 'fete-de-la-sience.appspot.com',
    iosClientId: '686444373137-78jubvt6vuvhanot5h9nj25tf67hndkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDev.RunnerTests',
  );
}
